export const DEFAULT_OPTIONS: Record<string, string[]> = {
  breakfast: ["oats", "bread", "fruit", "juice", "eggs", "other"],
  lunch: [
    "salad",
    "sandwich",
    "soup",
    "pasta",
    "rice dish",
    "meat & veg",
    "takeaway",
    "leftovers",
    "skipped",
    "other",
  ],
  dinner: [
    "salad",
    "sandwich",
    "soup",
    "pasta",
    "rice dish",
    "meat & veg",
    "takeaway",
    "leftovers",
    "skipped",
    "other",
  ],
  snacks: [
    "fruit",
    "crisps",
    "chocolate",
    "biscuits",
    "nuts",
    "yoghurt",
    "other",
    "none",
  ],
  tea: ["black", "green", "peppermint", "chamomile", "lemon & ginger"],
  alcohol: ["beer", "wine", "spirits"],
  exercise: ["running", "cycling", "yoga", "strength"],
};
